version: '3'

services:
  db:
    image: mariadb
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: videolibrary
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    image: psk/backend:1.0
    # restart: always
    environment:
      videolibrary.database.host: db
      videolibrary.database.port: 3306
      videolibrary.database.name: videolibrary
      videolibrary.database.user: root
      videolibrary.database.password: password
      server.port: 8080
      spring.jpa.hibernate.ddl-auto: update
    ports:
      - "8081:8080"
volumes:
  db_data: