version: '3'
name: videoteka_be
services:
  db:
    image: mariadb
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: videolibrary
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -ppassword" ]
      interval: 1s
      retries: 15

  backend:
    image: gustaszilinskas653/psk:backend
    container_name: backend
    environment:
      storage.rootStoragePath: /var/lib/uploads
      videolibrary.database.host: db
      server.port: 8080
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8080"
    volumes:
      - file_data:/var/lib/uploads
volumes:
  db_data:
  file_data: