name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Build the Docker image
      run: sh ./build/backend/build.sh

    - name: Build the Docker image
      run: ls
    - name: Build the Docker image
      run: git branch --show-current
      
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch
      
    - name: Create and push file
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Image push"
          git add ./images/psk_backend_latest.tar
          git commit -m "Update backend image"
          git push origin ${{ steps.extract_branch.outputs.branch }}
