name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Build the Docker image
      run: sh ./build/backend/build.sh
      
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch
      
    - name: Publish image
      env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
          date > ./images/generated.txt
          git remote add origin_with_token https://${{ secrets.PAT_TOKEN }}@github.com/edvinasstaupas/videoteka.git
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config user.password ${{ secrets.PAT_TOKEN }}
          git add .
          git commit -m "generated"
          git push origin_with_token HEAD:${{ steps.extract_branch.outputs.branch }}
          
    - run: ls ./images
