name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Navigate to builds
      run: cd ./build/backend
      
    - name: Build the Docker image
      run: sh build.sh
